package cn.porkchop.bos.service.impl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.10
 * 2018-03-20T16:04:58.740+08:00
 * Generated source version: 3.1.10
 * 
 */
@WebService(targetNamespace = "http://service.crm.porkchop.cn/", name = "CustomerService")
@XmlSeeAlso({})
public interface CustomerService {

    @WebMethod
    @RequestWrapper(localName = "findAll", targetNamespace = "http://service.crm.porkchop.cn/", className = "cn.porkchop.bos.FindAll")
    @ResponseWrapper(localName = "findAllResponse", targetNamespace = "http://service.crm.porkchop.cn/", className = "cn.porkchop.bos.FindAllResponse")
    @WebResult(name = "return", targetNamespace = "")
    java.util.List<Object> findAll();

    @WebMethod
    @RequestWrapper(localName = "findUnassociated", targetNamespace = "http://service.crm.porkchop.cn/", className = "cn.porkchop.bos.FindUnassociated")
    @ResponseWrapper(localName = "findUnassociatedResponse", targetNamespace = "http://service.crm.porkchop.cn/", className = "cn.porkchop.bos.FindUnassociatedResponse")
    @WebResult(name = "return", targetNamespace = "")
    java.util.List<Object> findUnassociated();

    @WebMethod
    @RequestWrapper(localName = "findByDecidedZoneId", targetNamespace = "http://service.crm.porkchop.cn/", className = "cn.porkchop.bos.FindByDecidedZoneId")
    @ResponseWrapper(localName = "findByDecidedZoneIdResponse", targetNamespace = "http://service.crm.porkchop.cn/", className = "cn.porkchop.bos.FindByDecidedZoneIdResponse")
    @WebResult(name = "return", targetNamespace = "")
    java.util.List<Object> findByDecidedZoneId(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0
    );
}
